[config]
version_check = false
caching = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

[templates.ags]
input_path = "~/.config/matugen/templates/ags.scss"
output_path = "~/.config/ags/colors.scss"

[templates.sway]
input_path = "~/.config/matugen/templates/sway.conf"
output_path = '~/.config/sway/colors.conf'

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.toml"
output_path = "~/.config/alacritty/colors.toml"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.fastfetch_logo_no_color]
input_path = "~/.config/matugen/templates/arch_logo_medium.txt"
output_path = "~/.config/fastfetch/arch_logo_medium.txt"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.mako]
input_path = "~/.config/matugen/templates/mako"
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.swaylock]
input_path = "~/.config/matugen/templates/swaylock"
output_path = '~/.swaylock/config'
