[general]
import = ["colors.toml"]

[window]
opacity = 0.3

[font]
normal = { family = "FiraCode Nerd Font", style = "Mono" }

[mouse]
    bindings = [
        { mouse = "Right", action = "Copy" },
    ]

[keyboard]
bindings = [
   { key = "T", mods = "Control", action = "SpawnNewInstance" }
]

